name: aethertftp
title: AetherTFTP
base: core24
adopt-info: aethertftp
summary: Modern lightweight TFTP GUI & CLI client and server
description: |
  AetherTFTP is a modern, lightweight, open-source cross-platform TFTP client and server application.
  Written in C++17 and utilizing the Qt 6 framework, it is designed for speed, reliability, and high-block-size network throughput.
license: MIT
contact: https://github.com/beratatmaca/AetherTFTP/issues
website: https://github.com/beratatmaca/AetherTFTP
source-code: https://github.com/beratatmaca/AetherTFTP

grade: stable
confinement: strict

apps:
  aethertftp:
    command: usr/local/bin/aethertftp
    plugs:
      - network
      - network-bind

  server-daemon:
    command: usr/local/bin/aethertftp --server --port 6969 --dir $SNAP_COMMON
    plugs:
      - network
      - network-bind
    daemon: simple
    restart-condition: on-failure

parts:
  aethertftp:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
    build-packages:
      - build-essential
      - qt6-base-dev
      - libgl1-mesa-dev
    stage-packages:
      - libqt6core6
      - libqt6network6
      - libqt6gui6t64
      - libqt6widgets6t64
      - libgl1
      - libegl1
      - libopengl0
      - libfontconfig1
      - libgraphite2-3
      - libharfbuzz0b
      - libmd4c0
    override-pull: |
      craftctl default
      base=$(tr -d '[:space:]' < VERSION)
      build=$(git rev-list --count HEAD)
      craftctl set version="${base}.${build}"
